### ISSUE TITLE
Variables with value are not blocked if only name is specified in settings

### ISSUE THREAD

**Issue by kravciak** [kubewarden/environment-variable-policy#13]
### Current Behavior

Description suggests that following settings would block ` envvar1="var1_value"`.
This is not true, pod is blocked only if defined variable is empty - `envvar1=""`.

```yaml
# In the following example, the resources that have least one of the variables will be denied:
settings:
  rules:
    - reject: anyIn
      environmentVariables:
        - name: "envvar1"
        - name: "envvar2"
```

### Expected Behavior

Not sure what is expected behavior, one of the following:
- fixed documentation to mention that policy blocks only when both `variable` and `value` match settings.
- fixed policy to block any value if only name is specified
