### ISSUE TITLE
Validating environment variables values from dynamic fields.

### ISSUE THREAD

**Issue by jvanz** [kubewarden/environment-variable-policy#5]
Kubernetes allow users to get container's environment variables values from other [resource field](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#envvar-v1-core). The fields  always refer to **Pod** fields, not high level resources (e.g. `Deployment`):

```
Selects a field of the pod: supports metadata.name, metadata.namespace, `metadata.labels['<KEY>']`, `metadata.annotations['<KEY>']`, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
```
From: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#envvarsource-v1-core

For example, using the following deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-nginx
  template:
    metadata:
      labels:
        app: template-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        env:
          - name: test
            valueFrom:
              fieldRef:
                fieldPath: "metadata.name"
```
As described in the docs, the pod running in the cluster have the environment variable `test` with the Pod name not the `Deployment` name:

```console
kubectl exec nginx-deployment-bf4589c7f-kmw8p -- env | grep test                                                                                                                                 
test=nginx-deployment-bf4589c7f-kmw8p
```

As Kubewarden is in the process of implementing audit checks calling the same function used to validate the resource in creation time by faking a create request. This can be a problem in the near future for this policy. If the audit checks load **high level resources** pod/container (e.g. like defined in the [PodTemplateSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podtemplatespec-v1-core)) data from the running pod/container, the policy can start reporting issue in the resources. Because some of this fields are dynamic. Like the pod name. 

Therefore, we need to find a workaround for this. Maybe disabling background checks.
